version: "3"

services:
  pastie:
    build: .
    command: bundle exec unicorn -c config/unicorn-docker.rb -E production
    environment:
      - RACK_ENV=production
      - PORT=8000
    ports:
      - "8000:8000"
    working_dir: /root/pastie
    volumes:
      - pastiedocuments:/root/pastie/public/documents
volumes:
  pastiedocuments:
    driver: local
