version: "3"

services:
  pastie:
    image: quickpay/pastie
    environment:
      - RACK_ENV=production
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - pastiedocuments:/root/pastie/public/documents
volumes:
  pastiedocuments:
    driver: local
