version: "3"

services:
  pastie:
    image: ruby:2.7
    command: sh -c "mkdir -p public/documents && gem install bundler:1.15.4 && bundle install && bundle exec unicorn -c config/unicorn.rb -E production"
    environment:
      - RACK_ENV=production
      - PORT=8000
    ports:
      - "8000:8000"
    working_dir: /root/pastie
    volumes:
      - .:/root/pastie:Z
